apiVersion: v1
kind: Service
metadata:
  name: pnttugas2
spec:
  selector:
    app: pnttugas2                
  ports:
  - protocol: TCP
    port: 80                      
    targetPort: 8080
    nodePort: 30007          
  type: LoadBalancer